name: Automated Tagging

on:
  push:
    branches:
      - main

permissions:
  contents: write 

jobs:
  tag:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Set Git Config
        run: |
          git config --local user.email "aasvigoswami0911@gmail.com"
          git config --local user.name "AasviGoswami"

      - name: Create Tag
        run: |
          git tag -a "v${{ github.run_number }}" -m "Release v${{ github.run_number }}"
          git push origin "v${{ github.run_number }}"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v${{ github.run_number }}'
          release_name: 'Release v${{ github.run_number }}'
          body: 'Description of the changes in this release'
